cc_test(
  name = "pie_test",
  srcs = glob(["*.cc", "idghv/*.cc", "mfv/*.cc"]),
  deps = [
         "//lib:pie",
         "//lib/idghv:idghv",
         "//lib/mfv:mfv",
        "@com_google_googletest//:gtest_main",
    ],
)